


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."active_settings" (
    "id" bigint NOT NULL,
    "egg_type" "text",
    "target_temperature" numeric,
    "target_humidity" numeric,
    "incubation_days" integer
);


ALTER TABLE "public"."active_settings" OWNER TO "postgres";


ALTER TABLE "public"."active_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."active_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."incubator_presets" (
    "id" bigint NOT NULL,
    "egg_type" "text" NOT NULL,
    "target_temperature" numeric,
    "target_humidity" numeric,
    "incubation_days" integer
);


ALTER TABLE "public"."incubator_presets" OWNER TO "postgres";


ALTER TABLE "public"."incubator_presets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."incubator_presets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."incubator_sessions" (
    "id" bigint NOT NULL,
    "egg_type" "text",
    "start_date" timestamp without time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'Active'::"text",
    "egg_quantity" integer DEFAULT 0 NOT NULL,
    "end_date" timestamp with time zone,
    "eggs_hatched" integer DEFAULT 0,
    "temperature" numeric
);


ALTER TABLE "public"."incubator_sessions" OWNER TO "postgres";


ALTER TABLE "public"."incubator_sessions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."incubator_sessions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sensor_readings" (
    "id" bigint NOT NULL,
    "current_temperature" numeric,
    "current_humidity" numeric,
    "recorded_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."sensor_readings" OWNER TO "postgres";


ALTER TABLE "public"."sensor_readings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sensor_readings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."active_settings"
    ADD CONSTRAINT "active_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."incubator_presets"
    ADD CONSTRAINT "incubator_presets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."incubator_sessions"
    ADD CONSTRAINT "incubator_sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sensor_readings"
    ADD CONSTRAINT "sensor_readings_pkey" PRIMARY KEY ("id");



CREATE POLICY "Allow all for authenticated users" ON "public"."incubator_sessions" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Anyone can insert active settings" ON "public"."active_settings" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can insert sensor readings" ON "public"."sensor_readings" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can insert sessions" ON "public"."incubator_sessions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can read active settings" ON "public"."active_settings" FOR SELECT USING (true);



CREATE POLICY "Anyone can read presets" ON "public"."incubator_presets" FOR SELECT USING (true);



CREATE POLICY "Anyone can read sensor readings" ON "public"."sensor_readings" FOR SELECT USING (true);



CREATE POLICY "Anyone can read sessions" ON "public"."incubator_sessions" FOR SELECT USING (true);



CREATE POLICY "Anyone can update active settings" ON "public"."active_settings" FOR UPDATE USING (true);



CREATE POLICY "Anyone can update sessions" ON "public"."incubator_sessions" FOR UPDATE USING (true);



CREATE POLICY "Authenticated users can insert settings" ON "public"."active_settings" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can read settings" ON "public"."active_settings" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can update settings" ON "public"."active_settings" FOR UPDATE TO "authenticated" USING (true);



ALTER TABLE "public"."active_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."incubator_presets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."incubator_sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sensor_readings" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."active_settings" TO "anon";
GRANT ALL ON TABLE "public"."active_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."active_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."active_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."active_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."active_settings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."incubator_presets" TO "anon";
GRANT ALL ON TABLE "public"."incubator_presets" TO "authenticated";
GRANT ALL ON TABLE "public"."incubator_presets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."incubator_presets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."incubator_presets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."incubator_presets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."incubator_sessions" TO "anon";
GRANT ALL ON TABLE "public"."incubator_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."incubator_sessions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."incubator_sessions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."incubator_sessions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."incubator_sessions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sensor_readings" TO "anon";
GRANT ALL ON TABLE "public"."sensor_readings" TO "authenticated";
GRANT ALL ON TABLE "public"."sensor_readings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sensor_readings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sensor_readings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sensor_readings_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































